Repository ibm-mas/cli, pull requests merged in 2023-08, with the labels that each got.

#401 [patch] Update AppConnect version info for HPU 8.6
  docs/catalogs/v8-230627-amd64.md
  docs/catalogs/v8-230721-amd64.md
  docs/catalogs/v8-230725-amd64.md
Labels: documentation

#409 [patch] Simplify workspace name restrictions
  docs/commands/install.md
  image/cli/mascli/functions/pipeline_config
Labels: Bug Fix

#411 [minor] Support cluster monitoring config without grafana
  Makefile
  docs/commands/install.md
  docs/guides/upgrade.md
  image/cli/mascli/functions/pipeline_config_advanced
  image/cli/mascli/functions/pipeline_show_config
  image/cli/mascli/functions/save_config
  image/cli/mascli/functions/utils
  image/cli/mascli/templates/pipelinerun.yaml
  mkdocs.yml
  tekton/src/params/install.yml.j2
  tekton/src/pipelines/taskdefs/cluster-setup/cluster-monitoring.yml.j2
  tekton/src/tasks/dependencies/cluster-monitoring.yml.j2
Labels: Enhancement

#419 [patch] Update disconnected install support position
  docs/guides/install.md
  image/cli/mascli/functions/pipeline_config_applications
  image/cli/mascli/mas
Labels: Documentation Update
