Repository ibm-mas/cli, pull requests merged in 2024-08, with the labels that each got.

#1160 [patch] update july docs and use @@MAS_LATEST_CATALOG@@
  build/bin/build-docs.sh
  docs/catalogs/v9-240730-amd64.md
  docs/commands/install.md
  docs/commands/mirror-images.md
  docs/commands/update.md
Labels: Documentation Update

#1168 [minor] Support ability to disable "WalkMe" guided tour feature
  docs/commands/install.md
  image/cli/mascli/functions/internal/save_config
  python/src/mas/cli/install/app.py
  python/src/mas/cli/install/argParser.py
  python/src/mas/cli/install/summarizer.py
  tekton/src/params/install.yml.j2
  tekton/src/pipelines/taskdefs/core/suite-install.yml.j2
  tekton/src/tasks/suite-install.yml.j2
Labels: Enhancement

#1206 [minor] Add Non-interactive install command builder
  python/src/mas/cli/install/app.py
  python/src/mas/cli/install/argBuilder.py
  python/src/mas/cli/install/argParser.py
  tekton/src/pipelines/taskdefs/ivt-core/common/taskref.yml.j2
Labels: Enhancement, High Priority

#1207 [patch] SNO compatibility fix for Manage advanced settings
  python/src/mas/cli/install/settings/manageSettings.py
Labels: Air Gap, Bug Fix

#1212 [patch] Add missing support for COS in non-interactive install
  docs/commands/install.md
  python/src/mas/cli/install/app.py
  python/src/mas/cli/install/argBuilder.py
  python/src/mas/cli/install/argParser.py
  python/src/mas/cli/install/summarizer.py
Labels: Bug Fix
